# Generated by Django 5.1.2 on 2025-05-19 21:43

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Ruta')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('TEMPORAL', 'Temporal')], default='WEEKLY', max_length=10, verbose_name='Frecuencia')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('week_start', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='Día de Inicio de la Semana')),
                ('week_end', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=6, verbose_name='Día de Fin de la Semana')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='RouteDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la Ruta')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre Ruta Diaria')),
                ('date_generated', models.DateField(auto_now_add=True, verbose_name='Fecha de Generación')),
            ],
            options={
                'verbose_name': 'Ruta Diaria',
                'verbose_name_plural': 'Rutas Diarias',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RouteDayClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Orden de Recogida')),
            ],
            options={
                'verbose_name': 'Cliente en Ruta Diaria',
                'verbose_name_plural': 'Clientes en Ruta Diaria',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRoute',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Nombre de la Ruta')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('TEMPORAL', 'Temporal')], default='WEEKLY', max_length=10, verbose_name='Frecuencia')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('week_start', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='Día de Inicio de la Semana')),
                ('week_end', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=6, verbose_name='Día de Fin de la Semana')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'historical Ruta',
                'verbose_name_plural': 'historical Rutas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
