# Generated by Django 5.1.2 on 2025-05-19 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('route', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='company.company', verbose_name='Compañía'),
        ),
        migrations.AddField(
            model_name='route',
            name='workers',
            field=models.ManyToManyField(related_name='routes', to='user.worker', verbose_name='Trabajadores'),
        ),
        migrations.AddField(
            model_name='routeday',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_days', to='route.route', verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='routedayclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='routedayclient',
            name='route_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_clients', to='route.routeday', verbose_name='Ruta Diaria'),
        ),
        migrations.AlterUniqueTogether(
            name='routeday',
            unique_together={('route', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='routedayclient',
            unique_together={('route_day', 'order')},
        ),
    ]
