# Generated by Django 5.1.2 on 2025-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deleted_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='modified_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='created_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='deleted_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='modified_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación'),
        ),
    ]
