# Generated by Django 5.1.2 on 2025-06-12 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteZoneDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('zones', models.JSONField(default=list, help_text='Lista de zonas asignadas a este día', verbose_name='Zonas')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_days', to='route.route', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Zona por Día de Ruta',
                'verbose_name_plural': 'Zonas por Día de Ruta',
                'unique_together': {('route', 'weekday')},
            },
        ),
    ]
