# Generated by Django 5.1.2 on 2025-03-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_owner_alter_historicalcompany_owner'),
        ('route', '0002_initial'),
        ('user', '0002_alter_client_companies_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroute',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Compañia'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='start_time',
            field=models.TimeField(verbose_name='Hora Inicial'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='route',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='company.company', verbose_name='Compañia'),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_time',
            field=models.TimeField(verbose_name='Hora Inicial'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='route',
            name='workers',
            field=models.ManyToManyField(related_name='routes', to='user.worker', verbose_name='Trabajadores'),
        ),
    ]
