# Generated by Django 5.1.2 on 2025-06-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_routezoneday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalroute',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='route',
            name='frequency',
        ),
    ]
