# Generated by Django 5.1.2 on 2025-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_remove_historicalroute_frequency_and_more'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routezoneday',
            name='zones',
        ),
        migrations.AddField(
            model_name='routezoneday',
            name='zones',
            field=models.ManyToManyField(related_name='route_zone_days', to='zone.zone', verbose_name='Zonas asignadas'),
        ),
    ]
