# Generated by Django 5.1.2 on 2025-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_remove_routezoneday_zones_routezoneday_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Deshabilitado'),
        ),
        migrations.AddField(
            model_name='route',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Deshabilitado'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='route',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='route',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación'),
        ),
    ]
