# Generated by Django 5.1.2 on 2026-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_historicalroute_disabled_route_disabled_and_more'),
        ('user', '0008_historicalworker_birth_date_worker_birth_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routedayclient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='routeday',
            name='date_generated',
        ),
        migrations.RemoveField(
            model_name='routeday',
            name='name',
        ),
        migrations.AddField(
            model_name='routeday',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AddField(
            model_name='routeday',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AddField(
            model_name='routeday',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planificada'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('PARTIAL', 'Parcial'), ('CANCELED', 'Cancelada')], default='PLANNED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='routedayclient',
            constraint=models.UniqueConstraint(fields=('route_day', 'order'), name='uniq_route_day_order'),
        ),
        migrations.AddConstraint(
            model_name='routedayclient',
            constraint=models.UniqueConstraint(fields=('route_day', 'client'), name='uniq_route_day_client'),
        ),
    ]
