# Generated by Django 5.1.2 on 2026-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_alter_routedayclient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeday',
            name='daily_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad Diaria (litros)'),
        ),
    ]
