# Generated by Django 5.1.2 on 2026-03-04

from django.db import migrations, models
import django.db.models.deletion


def _copy_first_worker_to_single_worker(apps, schema_editor):
    Route = apps.get_model('route', 'Route')
    for route in Route.objects.all().iterator():
        first_worker = route.workers.order_by('id').first()
        if first_worker:
            route.worker_id = first_worker.id
            route.save(update_fields=['worker'])


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_client_disabled_historicalclient_disabled_and_more'),
        ('route', '0008_routeday_daily_capacity_liters'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='worker',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='primary_routes',
                to='user.worker',
                verbose_name='Trabajador',
            ),
        ),
        migrations.RunPython(_copy_first_worker_to_single_worker, _noop_reverse),
        migrations.RemoveField(
            model_name='route',
            name='workers',
        ),
        migrations.AlterField(
            model_name='route',
            name='worker',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='routes',
                to='user.worker',
                verbose_name='Trabajador',
            ),
        ),
    ]
