# Generated by Django 5.1.2 on 2026-03-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyhub_historicalcompanyhub'),
        ('route', '0009_route_single_worker'),
        ('user', '0008_historicalworker_birth_date_worker_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='worker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.worker', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Compania'),
        ),
        migrations.AlterField(
            model_name='route',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='company.company', verbose_name='Compania'),
        ),
    ]
