# Generated by Django 5.1.2 on 2026-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0010_historicalroute_worker_alter_historicalroute_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalroute',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='route',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
    ]
