# Generated by Django 5.1.2 on 2026-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_alter_historicalroute_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeday',
            name='optimization_message',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Detalle de optimización'),
        ),
        migrations.AddField(
            model_name='routeday',
            name='optimization_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('OPTIMIZED', 'Optimizada'), ('FALLBACK', 'Orden alternativo'), ('FAILED', 'No optimizada')], default='PENDING', max_length=20, verbose_name='Estado de optimización'),
        ),
        migrations.AddField(
            model_name='routeday',
            name='optimized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última optimización'),
        ),
        migrations.AlterField(
            model_name='routeday',
            name='daily_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad por viaje (litros)'),
        ),
    ]
