# Generated by Django 5.1.2 on 2026-09-17 15:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_routeday_optimization_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='default_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacía, se utilizará la capacidad del camión asignado al trabajador.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacidad por viaje predeterminada (litros)'),
        ),
        migrations.AddField(
            model_name='route',
            name='default_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacía, se utilizará la capacidad del camión asignado al trabajador.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacidad por viaje predeterminada (litros)'),
        ),
    ]
