# Generated by Django 5.1.2 on 2026-03-19 10:13

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_companysettings_billing_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('fiscal_name', models.CharField(max_length=255, verbose_name='Razon social')),
                ('tax_id', models.CharField(max_length=20, verbose_name='CIF / NIF')),
                ('fiscal_address', models.CharField(max_length=255, verbose_name='Direccion fiscal')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Codigo postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, default='Espana', max_length=100, verbose_name='Pais')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='Persona de contacto')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'ordering': ('fiscal_name',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalBuyer',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('fiscal_name', models.CharField(max_length=255, verbose_name='Razon social')),
                ('tax_id', models.CharField(max_length=20, verbose_name='CIF / NIF')),
                ('fiscal_address', models.CharField(max_length=255, verbose_name='Direccion fiscal')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Codigo postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, default='Espana', max_length=100, verbose_name='Pais')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='Persona de contacto')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Comprador',
                'verbose_name_plural': 'historical Compradores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('sale_date', models.DateField(verbose_name='Fecha de venta')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de factura')),
                ('product_description', models.TextField(verbose_name='Producto / descripcion')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit', models.CharField(default='L', max_length=20, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Base imponible')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Importe IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Moneda')),
                ('invoice_year', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Ano factura')),
                ('invoice_sequence', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Secuencia factura')),
                ('invoice_number', models.CharField(blank=True, default='', editable=False, max_length=20, verbose_name='Numero de factura')),
                ('invoice_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Factura PDF')),
                ('invoice_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Factura generada en')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('buyer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.buyer', verbose_name='Comprador')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Venta',
                'verbose_name_plural': 'historical Ventas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('sale_date', models.DateField(verbose_name='Fecha de venta')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de factura')),
                ('product_description', models.TextField(verbose_name='Producto / descripcion')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit', models.CharField(default='L', max_length=20, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Base imponible')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Importe IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Moneda')),
                ('invoice_year', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Ano factura')),
                ('invoice_sequence', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Secuencia factura')),
                ('invoice_number', models.CharField(blank=True, default='', editable=False, max_length=20, verbose_name='Numero de factura')),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='sales/invoices/', verbose_name='Factura PDF')),
                ('invoice_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Factura generada en')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sale.buyer', verbose_name='Comprador')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ('-invoice_date', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='buyer',
            constraint=models.UniqueConstraint(fields=('company', 'tax_id'), name='uniq_buyer_tax_id_per_company'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_year', 'invoice_sequence'), name='uniq_sale_invoice_sequence'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_sale_invoice_number'),
        ),
    ]
