# Generated by Django 5.1.2 on 2026-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalbuyer',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalbuyer',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalbuyer',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
    ]
