# Generated by Django 5.1.2 on 2026-07-09 09:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def copy_existing_sales_to_lines(apps, schema_editor):
    Sale = apps.get_model("sale", "Sale")
    SaleLine = apps.get_model("sale", "SaleLine")

    lines = [
        SaleLine(
            sale_id=sale.id,
            position=0,
            product_description=sale.product_description,
            quantity=sale.quantity,
            unit=sale.unit,
            unit_price=sale.unit_price,
            tax_rate=sale.tax_rate,
            subtotal=sale.subtotal,
            tax_amount=sale.tax_amount,
            total=sale.total,
        )
        for sale in Sale.objects.all().iterator()
    ]
    SaleLine.objects.bulk_create(lines, batch_size=500)


def remove_copied_lines(apps, schema_editor):
    apps.get_model("sale", "SaleLine").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_buyer_created_date_alter_buyer_deleted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posicion')),
                ('product_description', models.TextField(verbose_name='Producto / descripcion')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit', models.CharField(default='L', max_length=20, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA %')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Base imponible')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Importe IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Total')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sale.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Linea de venta',
                'verbose_name_plural': 'Lineas de venta',
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('sale', 'position'), name='uniq_sale_line_position')],
            },
        ),
        migrations.RunPython(
            copy_existing_sales_to_lines,
            remove_copied_lines,
        ),
    ]
