# Generated by Django 5.1.2 on 2026-08-10 19:36

import hashlib
import json

import django.db.models.deletion
from django.db import migrations, models


SNAPSHOT_FIELDS = (
    "billing_business_name",
    "billing_tax_id",
    "billing_address",
    "billing_postal_code",
    "billing_city",
    "billing_province",
    "billing_country",
    "billing_phone",
    "billing_email",
    "billing_bank_account",
    "billing_logo",
    "billing_ler_code",
    "billing_footer",
)


def _file_name(file_field):
    return getattr(file_field, "name", "") or str(file_field or "")


def _hash_data(data):
    normalized = {
        field: str(data.get(field) or "")
        for field in SNAPSHOT_FIELDS
    }
    raw = json.dumps(normalized, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _snapshot_data(company, settings_obj):
    return {
        "billing_business_name": (
            (settings_obj.billing_business_name if settings_obj else "")
            or company.name
            or ""
        ),
        "billing_tax_id": (
            (settings_obj.billing_tax_id if settings_obj else "")
            or company.cif
            or ""
        ),
        "billing_address": (
            (settings_obj.billing_address if settings_obj else "")
            or company.address
            or ""
        ),
        "billing_postal_code": (settings_obj.billing_postal_code if settings_obj else "") or "",
        "billing_city": (settings_obj.billing_city if settings_obj else "") or "",
        "billing_province": (settings_obj.billing_province if settings_obj else "") or "",
        "billing_country": (settings_obj.billing_country if settings_obj else "") or "Espana",
        "billing_phone": (
            (settings_obj.billing_phone if settings_obj else "")
            or company.phone
            or ""
        ),
        "billing_email": (
            (settings_obj.billing_email if settings_obj else "")
            or company.email
            or ""
        ),
        "billing_bank_account": (settings_obj.billing_bank_account if settings_obj else "") or "",
        "billing_logo": (
            _file_name(settings_obj.billing_logo) if settings_obj else ""
        ) or _file_name(company.logo),
        "billing_ler_code": (settings_obj.billing_ler_code if settings_obj else "") or "",
        "billing_footer": (settings_obj.billing_footer if settings_obj else "") or "",
    }


def populate_sale_invoice_issuer_snapshots(apps, schema_editor):
    CompanySettings = apps.get_model("company", "CompanySettings")
    Sale = apps.get_model("sale", "Sale")
    SaleInvoiceIssuerSnapshot = apps.get_model("sale", "SaleInvoiceIssuerSnapshot")

    for sale in Sale.objects.select_related("company").filter(invoice_issuer__isnull=True).iterator():
        settings_obj = CompanySettings.objects.filter(company_id=sale.company_id).first()
        data = _snapshot_data(sale.company, settings_obj)
        data_hash = _hash_data(data)
        snapshot = SaleInvoiceIssuerSnapshot.objects.filter(
            company_id=sale.company_id,
            data_hash=data_hash,
        ).first()
        if snapshot is None:
            snapshot = SaleInvoiceIssuerSnapshot.objects.create(
                company_id=sale.company_id,
                data_hash=data_hash,
                **data,
            )
        Sale.objects.filter(pk=sale.pk).update(invoice_issuer_id=snapshot.id)


def clear_sale_invoice_issuer_snapshots(apps, schema_editor):
    Sale = apps.get_model("sale", "Sale")
    SaleInvoiceIssuerSnapshot = apps.get_model("sale", "SaleInvoiceIssuerSnapshot")

    Sale.objects.update(invoice_issuer=None)
    SaleInvoiceIssuerSnapshot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_created_date_and_more'),
        ('sale', '0003_saleline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoiceIssuerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_business_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Razon social')),
                ('billing_tax_id', models.CharField(blank=True, default='', max_length=20, verbose_name='CIF')),
                ('billing_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Direccion fiscal')),
                ('billing_postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Codigo postal')),
                ('billing_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad')),
                ('billing_province', models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia')),
                ('billing_country', models.CharField(blank=True, default='Espana', max_length=100, verbose_name='Pais')),
                ('billing_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono')),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('billing_bank_account', models.CharField(blank=True, default='', max_length=64, verbose_name='Cuenta bancaria')),
                ('billing_logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='sale/issuer_snapshots/', verbose_name='Logo facturacion')),
                ('billing_ler_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Codigo LER')),
                ('billing_footer', models.TextField(blank=True, default='', verbose_name='Pie de factura')),
                ('data_hash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='Hash de datos')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoice_issuer_snapshots', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Datos fiscales de factura',
                'verbose_name_plural': 'Datos fiscales de facturas',
                'ordering': ('-created_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='invoice_issuer',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.saleinvoiceissuersnapshot', verbose_name='Datos fiscales de factura'),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_issuer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sale.saleinvoiceissuersnapshot', verbose_name='Datos fiscales de factura'),
        ),
        migrations.RunPython(
            populate_sale_invoice_issuer_snapshots,
            clear_sale_invoice_issuer_snapshots,
        ),
        migrations.AddConstraint(
            model_name='saleinvoiceissuersnapshot',
            constraint=models.UniqueConstraint(fields=('company', 'data_hash'), name='uniq_sale_invoice_snapshot_company_hash'),
        ),
    ]
