# Generated by Django 5.1.2 on 2026-08-19 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_saleinvoiceissuersnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='invoice_issuer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sale.saleinvoiceissuersnapshot', verbose_name='Datos fiscales de factura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sale.saleinvoiceissuersnapshot', verbose_name='Datos fiscales de factura'),
        ),
    ]
