# Generated by Django 5.1.2 on 2026-09-30 10:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_historicalsale_invoice_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='unit_price',
            field=models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio unitario'),
        ),
    ]
