# Generated by Django 5.1.2 on 2025-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
    ]
