# Generated by Django 5.1.2 on 2025-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_owner_alter_historicalcompany_owner'),
        ('user', '0002_alter_client_companies_alter_client_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cif',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='cif',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='España', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='client',
            name='dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='country',
            field=models.CharField(blank=True, default='España', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
