# Generated by Django 5.1.2 on 2025-06-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_client_name_alter_historicalclient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Cada semana'), ('2_WEEKS', 'Cada 2 semanas'), ('3_WEEKS', 'Cada 3 semanas'), ('4_WEEKS', 'Cada 4 semanas')], default='WEEKLY', max_length=10, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='client',
            name='zone',
            field=models.CharField(blank=True, help_text='Zona geográfica del cliente (ej: Bermejales, Triana, Los Remedios)', max_length=100, verbose_name='Zona'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='frequency',
            field=models.CharField(choices=[('WEEKLY', 'Cada semana'), ('2_WEEKS', 'Cada 2 semanas'), ('3_WEEKS', 'Cada 3 semanas'), ('4_WEEKS', 'Cada 4 semanas')], default='WEEKLY', max_length=10, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='zone',
            field=models.CharField(blank=True, help_text='Zona geográfica del cliente (ej: Bermejales, Triana, Los Remedios)', max_length=100, verbose_name='Zona'),
        ),
        migrations.DeleteModel(
            name='ClientPickupSchedule',
        ),
    ]
