# Generated by Django 5.1.2 on 2025-06-14 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('user', '0003_client_frequency_client_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='company.company', verbose_name='Empresa'),
        ),
    ]
