# Generated by Django 5.1.2 on 2025-05-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_owner_alter_historicalcompany_owner'),
        ('user', '0003_remove_client_adress_remove_client_cif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='clients', to='company.company', verbose_name='Empresa'),
        ),
    ]
