# Generated by Django 5.1.2 on 2025-06-16 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_worker_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='zone',
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
