# Generated by Django 5.1.2 on 2025-05-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_client_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='cif',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIF'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='cif',
            field=models.CharField(blank=True, max_length=20, verbose_name='CIF'),
        ),
    ]
