# Generated by Django 5.1.2 on 2025-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_client_latitude_remove_client_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='workers/', verbose_name='Foto'),
        ),
    ]
