# Generated by Django 5.1.2 on 2025-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_client_disabled_historicalclient_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworker',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
