# Generated by Django 5.1.2 on 2026-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_historicalworker_birth_date_worker_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalworker',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalworker',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalworker',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
    ]
