# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_client_created_date_alter_client_deleted_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalclient",
            name="photo",
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name="Foto"),
        ),
        migrations.AddField(
            model_name="client",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="clients/", verbose_name="Foto"),
        ),
    ]
