# Generated by Django 5.1.2 on 2026-02-03 18:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_disabled_historicalcompany_disabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Hub')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Ubicación')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Hub de Empresa',
                'verbose_name_plural': 'Hubs de Empresas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompanyHub',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Hub')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Ubicación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Hub de Empresa',
                'verbose_name_plural': 'historical Hubs de Empresas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
