# Generated by Django 5.1.2 on 2026-03-16 17:57

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyhub_historicalcompanyhub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('default_price_per_liter', models.DecimalField(decimal_places=3, default=Decimal('1.200'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio global por litro')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Configuracion de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompanySettings',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('default_price_per_liter', models.DecimalField(decimal_places=3, default=Decimal('1.200'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio global por litro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Configuracion de Empresa',
                'verbose_name_plural': 'historical Configuraciones de Empresa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
