# Generated by Django 5.1.2 on 2026-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companysettings_historicalcompanysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='billing_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Direccion fiscal'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_bank_account',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_business_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razon social'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_country',
            field=models.CharField(blank=True, default='Espana', max_length=100, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_footer',
            field=models.TextField(blank=True, default='', verbose_name='Pie de factura'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_ler_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Codigo LER'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='company/billing/', verbose_name='Logo facturacion'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Codigo postal'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='billing_tax_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CIF'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Direccion fiscal'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_bank_account',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_business_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razon social'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_country',
            field=models.CharField(blank=True, default='Espana', max_length=100, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_footer',
            field=models.TextField(blank=True, default='', verbose_name='Pie de factura'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_ler_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Codigo LER'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_logo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Logo facturacion'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Codigo postal'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='billing_tax_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CIF'),
        ),
    ]
