# Generated by Django 5.1.2 on 2026-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='company',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='companyhub',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='companyhub',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='companyhub',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompanyhub',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompanyhub',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompanyhub',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompanysettings',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompanysettings',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalcompanysettings',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
    ]
