# Generated by Django 5.1.2 on 2026-09-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_company_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='collections_enabled',
            field=models.BooleanField(default=True, verbose_name='Modulo de recogidas activo'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='wholesale_purchases_enabled',
            field=models.BooleanField(default=True, verbose_name='Modulo de compras al por mayor activo'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='collections_enabled',
            field=models.BooleanField(default=True, verbose_name='Modulo de recogidas activo'),
        ),
        migrations.AddField(
            model_name='historicalcompanysettings',
            name='wholesale_purchases_enabled',
            field=models.BooleanField(default=True, verbose_name='Modulo de compras al por mayor activo'),
        ),
    ]
