# Generated by Django 5.1.2 on 2026-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_bulk_collection_flags_and_conversion_factors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='bulk_collections_enabled',
            field=models.BooleanField(default=True, verbose_name='Modulo de recogidas al por mayor activo'),
        ),
        migrations.AlterField(
            model_name='historicalcompanysettings',
            name='bulk_collections_enabled',
            field=models.BooleanField(default=True, verbose_name='Modulo de recogidas al por mayor activo'),
        ),
    ]
