# Generated by Django 5.1.2 on 2026-09-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_companysettings_bulk_collections_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='liters_per_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcompanysettings',
            name='liters_per_unit',
        ),
    ]
