# Generated by Django 5.1.2 on 2025-08-19 16:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTruck',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('registration_number', models.CharField(max_length=255, verbose_name='Matrícula')),
                ('brand', models.CharField(blank=True, max_length=64, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('IN_SERVICE', 'En servicio'), ('MAINTENANCE', 'Mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('DECOMMISSIONED', 'Retirado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('fuel', models.CharField(blank=True, choices=[('DIESEL', 'Diésel'), ('PETROL', 'Gasolina'), ('ELECTRIC', 'Eléctrico'), ('HYBRID', 'Híbrido')], max_length=20, null=True, verbose_name='Combustible')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Empresa')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Camión',
                'verbose_name_plural': 'historical Camiones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('registration_number', models.CharField(max_length=255, verbose_name='Matrícula')),
                ('brand', models.CharField(blank=True, max_length=64, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('IN_SERVICE', 'En servicio'), ('MAINTENANCE', 'Mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('DECOMMISSIONED', 'Retirado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('fuel', models.CharField(blank=True, choices=[('DIESEL', 'Diésel'), ('PETROL', 'Gasolina'), ('ELECTRIC', 'Eléctrico'), ('HYBRID', 'Híbrido')], max_length=20, null=True, verbose_name='Combustible')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='company.company', verbose_name='Empresa')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
            },
        ),
    ]
