# Generated by Django 5.1.2 on 2025-09-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_historicaltruck_disabled_truck_disabled_and_more'),
        ('user', '0008_historicalworker_birth_date_worker_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltruck',
            name='driver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.worker', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck', to='user.worker', verbose_name='Conductor'),
        ),
    ]
