# Generated by Django 5.1.2 on 2025-10-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_alter_historicaltruck_driver_alter_truck_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltruck',
            name='registration_number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Matrícula'),
        ),
    ]
