# Generated by Django 5.1.2 on 2026-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_alter_historicaltruck_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltruck',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='capacity',
        ),
        migrations.AddField(
            model_name='historicaltruck',
            name='capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad (litros)'),
        ),
        migrations.AddField(
            model_name='truck',
            name='capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad (litros)'),
        ),
    ]
