# Generated by Django 5.1.2 on 2026-09-24

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0007_alter_company_created_date_and_more"),
        ("user", "0010_historicalclient_photo_client_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalWholesalePurchase",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("disabled", models.BooleanField(default=False, verbose_name="Deshabilitado")),
                ("created_date", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Fecha de Creacion")),
                ("modified_date", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Fecha de Modificacion")),
                ("deleted_date", models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Fecha de Eliminacion")),
                ("purchase_date", models.DateField(verbose_name="Fecha de compra")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Concepto")),
                ("unit", models.CharField(choices=[("KG", "Kilogramos"), ("UD", "Unidades"), ("L", "Litros")], max_length=2, verbose_name="Unidad")),
                ("calculation_mode", models.CharField(choices=[("TOTAL", "Calcular importe final"), ("UNIT_PRICE", "Calcular precio unitario"), ("QUANTITY", "Calcular cantidad")], default="TOTAL", max_length=20, verbose_name="Valor calculado")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))], verbose_name="Cantidad")),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))], verbose_name="Precio unitario")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))], verbose_name="Importe final")),
                ("billable", models.BooleanField(default=True, verbose_name="Facturable")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observaciones")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                ("history_type", models.CharField(choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1)),
                ("client", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="user.client", verbose_name="Cliente")),
                ("company", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="company.company", verbose_name="Empresa")),
                ("history_user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "historical Compra al por mayor",
                "verbose_name_plural": "historical Compras al por mayor",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WholesalePurchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("disabled", models.BooleanField(default=False, verbose_name="Deshabilitado")),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True, verbose_name="Fecha de Creacion")),
                ("modified_date", models.DateTimeField(auto_now=True, null=True, verbose_name="Fecha de Modificacion")),
                ("deleted_date", models.DateTimeField(auto_now=True, null=True, verbose_name="Fecha de Eliminacion")),
                ("purchase_date", models.DateField(verbose_name="Fecha de compra")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Concepto")),
                ("unit", models.CharField(choices=[("KG", "Kilogramos"), ("UD", "Unidades"), ("L", "Litros")], max_length=2, verbose_name="Unidad")),
                ("calculation_mode", models.CharField(choices=[("TOTAL", "Calcular importe final"), ("UNIT_PRICE", "Calcular precio unitario"), ("QUANTITY", "Calcular cantidad")], default="TOTAL", max_length=20, verbose_name="Valor calculado")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))], verbose_name="Cantidad")),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))], verbose_name="Precio unitario")),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))], verbose_name="Importe final")),
                ("billable", models.BooleanField(default=True, verbose_name="Facturable")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Observaciones")),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wholesale_purchases", to="user.client", verbose_name="Cliente")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wholesale_purchases", to="company.company", verbose_name="Empresa")),
            ],
            options={
                "verbose_name": "Compra al por mayor",
                "verbose_name_plural": "Compras al por mayor",
                "ordering": ("-purchase_date", "-id"),
                "indexes": [models.Index(fields=["company", "purchase_date"], name="wholesale_company_date_idx"), models.Index(fields=["company", "billable"], name="wholesale_company_bill_idx")],
            },
        ),
    ]
