# Generated by Django 5.1.2 on 2026-09-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwholesalepurchase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wholesalepurchase',
            name='description',
        ),
        migrations.AddField(
            model_name='historicalwholesalepurchase',
            name='invoice_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Factura adjunta'),
        ),
        migrations.AddField(
            model_name='wholesalepurchase',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='wholesale/invoices/', verbose_name='Factura adjunta'),
        ),
    ]
