# Generated by Django 5.1.2 on 2026-09-24 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_companysettings_bulk_collections_enabled_and_more'),
        ('user', '0010_historicalclient_photo_client_photo'),
        ('wholesale', '0003_rename_wholesale_purchase_to_bulk_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbulkcollection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Recogida al por mayor', 'verbose_name_plural': 'historical Recogidas al por mayor'},
        ),
        migrations.RemoveIndex(
            model_name='bulkcollection',
            name='wholesale_company_date_idx',
        ),
        migrations.AlterField(
            model_name='bulkcollection',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_collections', to='user.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='bulkcollection',
            name='collection_date',
            field=models.DateField(verbose_name='Fecha de recogida'),
        ),
        migrations.AlterField(
            model_name='bulkcollection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_collections', to='company.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalbulkcollection',
            name='collection_date',
            field=models.DateField(verbose_name='Fecha de recogida'),
        ),
        migrations.AddIndex(
            model_name='bulkcollection',
            index=models.Index(fields=['company', 'collection_date'], name='wholesale_company_date_idx'),
        ),
    ]
