# Generated by Django 5.1.2 on 2026-09-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_alter_historicalbulkcollection_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bulkcollection',
            new_name='bulk_company_date_idx',
            old_name='wholesale_company_date_idx',
        ),
        migrations.RenameIndex(
            model_name='bulkcollection',
            new_name='bulk_company_bill_idx',
            old_name='wholesale_company_bill_idx',
        ),
    ]
