MESSAGE = 'Mensaje'
PASSWORD_SUCCESSFULLY_UPDATED = 'Contraseña actualizada correctamente'
DETAILS = 'Detalles'
ERRORS = 'Errores'
ERROR = 'Error'
ERRORS_IN_THE_INFORMATION = 'Hay errores en la información enviada'
USER_SUCCESSFULLY_REGISTERED = 'Usuario registrado correctamente.'
ERRORS_IN_REGISTRATION = 'Hay errores en el registro'
USER_SUCCESSFULLY_DELETED = 'Usuario eliminado correctamente'
USER_APP = 'USER_APP'
BASE_URL = 'http://localhost:8000'
GOOGLE_LOGIN_FAILED = 'Failed to get token from Google'
INCORRECT_CREDENTIALS = 'Contraseña o nombre de usuario incorrectos'
USER_DOESNT_EXISTS = 'No existe este usuario.'
SUCCESSFULL_LOGOUT = 'Sesión cerrada correctamente.'
INTERNAL_ERROR = 'Error interno:'
USER_NOT_FOUND = 'Usuario no encontrado'
INVALID_EMAIL_RECEIVED = 'Email inválido recibido de Google'
INVALID_GOOGLE_ID_TOKEN = 'ID token de Google inválido'
SUCCESSFULL_LOGIN = 'Inicio de sesion correcto.'
CREDENTIAL_OR_TOKEN_REQUIRED = 'credential o token requerido'
ACCESS_EMAIL_SUBJECT_USER = 'Acceso a GreenPath como Usuario'
MAX_CLIENTS_PER_DAY = 15

#Empresas
ERROR_CREATING_COMPANY = 'Error creando empresa'
ONLY_OWNERS_CAN_CREATE_COMPANIES = 'Solo los dueños pueden crear empresas'
COMPANY_SETTINGS_UPDATED = 'Configuracion de empresa actualizada correctamente.'
COMPANY_SETTINGS_FORBIDDEN = 'Solo owner o worker de la empresa pueden consultar esta configuracion.'
COMPANY_SETTINGS_UPDATE_FORBIDDEN = 'Solo los dueños pueden actualizar la configuracion de empresa.'
COMPANY_SETTINGS_NOT_FOUND = 'No se ha encontrado una empresa asociada al usuario.'

#Trabajadores
ERROR_CREATING_WORKER = 'Error creando trabajador'
ONLY_OWNERS_CAN_CREATE_WORKERS = 'Solo los dueños pueden crear trabajadores'
ALREADY_ACTIVE_WORKER = 'El trabajador ya está activo'

#Clientes
ERROR_CREATING_CLIENT = 'Error creando cliente'
ONLY_OWNERS_CAN_CREATE_CLIENTS = 'Solo los dueños pueden crear clientes'
USER_COMPANY_DOES_NOT_EXIST = 'El usuario no tiene una empresa asociada'
CLIENT_NOT_FOUND = 'Cliente no encontrado'

#Rutas
ERROR_CREATING_ROUTE = 'Error creando ruta'
ONLY_OWNERS_CAN_CREATE_ROUTES = 'Solo los dueños pueden crear rutas'
NOT_ROUTE_IN_RANGE = 'No se generaron rutas para el rango dado.'
SUCCESFULY_GENERATE_ROUTES = 'Ritas generadas correctamente'
DATE_NOT_VALID = 'Fechas o configuración de zonas inválidas.'
WEEKLY_OPERATIONAL_ROUTE_GENERATED = 'Semana operativa generada correctamente.'
ROUTE_WEEK_GENERATION_IN_PROGRESS = 'Ya hay una generacion de semana en curso para esta ruta.'
ROUTE_GENERATION_FORBIDDEN = 'Solo owner o worker de la empresa pueden generar rutas operativas.'
ROUTE_WEEK_OUTSIDE_ROUTE_RANGE = 'La semana solicitada esta fuera del rango de fechas de la ruta.'
GENERATE_WEEK_CAPACITY_REQUIRED = 'Debes indicar `daily_capacity_liters` global o `days` con capacidades por fecha.'
GENERATE_WEEK_CAPACITY_MUTUALLY_EXCLUSIVE = 'No puedes enviar `daily_capacity_liters` y `days` al mismo tiempo.'
GENERATE_WEEK_DAYS_DUPLICATED = 'Hay fechas duplicadas en `days`.'
GENERATE_WEEK_DAYS_OUTSIDE_WEEK = 'Todas las fechas de `days` deben estar dentro de la semana indicada.'
ROUTE_ZONE_CONFIG_DAY_INVALID = 'Dia no valido. Debe estar entre 0 (lunes) y 6 (domingo).'
ROUTE_ZONE_CONFIG_KEY_INVALID = 'Clave no valida. Debe ser un numero entre 0 y 6.'
ROUTE_DAY_DATE_PAST_INVALID = 'La fecha no puede ser anterior a hoy'
ROUTE_GOOGLE_NO_VALID_ROUTE = 'Google Maps no devolvio una ruta valida.'
ROUTE_END_DATE_BEFORE_START_DATE = 'La fecha de fin no puede ser anterior a la fecha de inicio.'
ROUTE_ZONE_DAYS_DUPLICATED = 'No se puede repetir el mismo dia de la semana en zone_days.'
ROUTE_ZONE_WEEKDAY_INVALID = 'El weekday indicado no es valido.'
ROUTE_WORKER_COMPANY_INVALID = 'El trabajador seleccionado no pertenece a tu empresa.'
ROUTE_ZONE_CONFIG_UPDATED = 'Configuracion de zonas actualizada correctamente.'
ROUTE_DAY_NOT_FOUND = 'Ruta diaria no encontrada para esta ruta.'
ROUTE_DAY_CLIENT_NOT_FOUND = 'Parada no encontrada para esta ruta diaria.'
ROUTE_DAY_START_SUCCESS = 'Ruta diaria iniciada correctamente.'
ROUTE_DAY_FINISH_SUCCESS = 'Ruta diaria finalizada correctamente.'
ROUTE_DAY_STOP_COMPLETED_SUCCESS = 'Parada registrada correctamente.'
ROUTE_DAY_GOOGLE_NAVIGATION_READY = 'Enlace de navegacion generado correctamente.'
ROUTE_DAY_START_INVALID_STATUS = 'Solo se puede iniciar una ruta diaria planificada o parcial.'
ROUTE_DAY_FINISH_INVALID_STATUS = 'Solo se puede finalizar una ruta diaria en progreso.'
ROUTE_DAY_STOP_ROUTE_NOT_STARTED = 'Debes iniciar la ruta diaria antes de registrar una parada.'
ROUTE_DAY_STOP_ALREADY_COMPLETED = 'La parada ya tiene una recogida registrada.'
ROUTE_DAY_STOP_OUT_OF_ORDER = 'Debes registrar primero las paradas anteriores.'
ROUTE_DAY_GOOGLE_NAVIGATION_EMPTY = 'No hay paradas con ubicacion para generar navegacion.'
ROUTE_DAY_GOOGLE_HUB_REQUIRED = 'Debes configurar la nave (hub) para exportar la navegacion.'
ROUTE_DAY_FINISH_DECISION_REQUIRED = 'Quedan paradas pendientes. Debes elegir cerrar la ruta diaria como parcial o cancelada.'
ROUTE_DAY_FINISH_CLOSE_ACTION_INVALID = 'La accion de cierre no es valida. Usa PARTIAL o CANCELED.'
ROUTE_DAY_GENERATION_LOCKED = 'No puedes modificar una ruta diaria ya iniciada, parcial o completada.'
ROUTE_WEEK_REGENERATION_LOCKED = 'No puedes regenerar una semana que contiene rutas diarias ya iniciadas, parciales o completadas.'

#Recogida
ERROR_CREATING_COLLECTION = 'Error creando recogida'
ONLY_OWNERS_AND_WORKERS_CAN_REGISTER_COLLECTIONS = 'Solo los dueños y trabajadores pueden registrar recogidas'
COLLECTION_REQUEST_ANSWERED_SUCCESS = 'Solicitud de recogida respondida correctamente.'
COLLECTION_REQUEST_MANUAL_SUCCESS = 'Solicitud de recogida actualizada manualmente.'
COLLECTION_REQUEST_NOT_FOUND = 'Solicitud de recogida no encontrada.'
COLLECTION_REQUEST_NOT_PENDING = 'La solicitud no esta pendiente.'
COLLECTION_REQUEST_EXPIRED = 'La solicitud ya ha expirado.'
COLLECTION_REQUEST_CLIENT_FORBIDDEN = 'Solo el cliente propietario puede responder esta solicitud.'
COLLECTION_REQUEST_MANUAL_FORBIDDEN = 'Solo owner o worker pueden registrar litros manualmente.'
COLLECTION_REQUEST_FINAL_LITERS_REQUIRED = 'Debes indicar los litros finales.'
COLLECTION_REQUEST_FINAL_LITERS_INVALID = 'Los litros finales deben ser mayores que 0.'
COLLECTION_REQUEST_COMPANY_FORBIDDEN = 'La solicitud no pertenece a tu empresa.'
COLLECTION_REQUEST_TOO_LATE = 'La fecha de recogida ya ha pasado para esta solicitud.'
COLLECTION_REQUEST_CLIENT_LIST_FORBIDDEN = 'Solo clientes pueden consultar sus solicitudes.'
COLLECTION_REQUEST_NOTIFY_SUBJECT = 'Nueva solicitud de estimacion de recogida'
COLLECTION_REQUEST_NOTIFY_BODY = 'Hola, tienes una solicitud de estimacion para la ruta {route_name} del dia {route_date}. Por favor responde antes de {expires_at}.'
COLLECTION_DEDUCTION_LITERS_INVALID = 'Los litros descontados no pueden ser mayores que los litros medidos.'

#Dashboard
ERROR_GETTING_DASHBOARD_DATA = 'Error obteniendo datos del dashboard'

#Camiones
ERROR_CREATING_TRUCK = 'Error creando camión'
ONLY_OWNERS_CAN_CREATE_TRUCKS = 'Solo los dueños pueden crear camiones'
NEED_COMPANY_FOR_TRUCK_CREATION = 'Debes indicar la empresa para crear un camión'
DRIVER_TRUCK_SAME_COMPANY = 'El conductor debe pertenecer a la misma empresa que el camión'
ONLY_UPDATE_TRUCKS_SAME_COMPANY = 'Solo puedes actualizar camiones de tu empresa'
ALREADY_HAVE_DRIVER = 'El camión ya tiene un conductor asignado'
