# Generated by Django 5.1.2 on 2025-05-19 21:43

import django.core.validators
import simple_history.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('collection_date', models.DateField(verbose_name='Fecha de Recogida')),
                ('container_type', models.CharField(choices=[('BIDONES', 'Bidones (60L)'), ('IBC', 'IBC (1000L)')], default='BIDONES', max_length=10, verbose_name='Tipo de Envase')),
                ('container_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Envases')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por Litro')),
                ('liters_collected', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Litros Recolectados')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Precio Total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Recogida',
                'verbose_name_plural': 'Recogidas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCollection',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('collection_date', models.DateField(verbose_name='Fecha de Recogida')),
                ('container_type', models.CharField(choices=[('BIDONES', 'Bidones (60L)'), ('IBC', 'IBC (1000L)')], default='BIDONES', max_length=10, verbose_name='Tipo de Envase')),
                ('container_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Envases')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por Litro')),
                ('liters_collected', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Litros Recolectados')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Precio Total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Recogida',
                'verbose_name_plural': 'historical Recogidas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
