# Generated by Django 5.1.2 on 2025-05-19 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('route', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='user.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='collection',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='route.route', verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='collection',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='user.worker', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='route',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='route.route', verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='worker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.worker', verbose_name='Trabajador'),
        ),
    ]
