# Generated by Django 5.1.2 on 2025-03-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
        ('route', '0003_alter_historicalroute_company_and_more'),
        ('user', '0002_alter_client_companies_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='user.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateTimeField(verbose_name='Fecha de Recogida'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='liters_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros Recolectados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio por Litro'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='route.route', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='user.worker', verbose_name='Trabajador'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='collection_date',
            field=models.DateTimeField(verbose_name='Fecha de Recogida'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='liters_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros Recolectados'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio por Litro'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='route',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='route.route', verbose_name='Ruta'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='worker',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user.worker', verbose_name='Trabajador'),
        ),
    ]
