# Generated by Django 5.1.2 on 2025-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='liters_collected',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Litros Recolectados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='liters_collected',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Litros Recolectados'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Precio Total'),
        ),
    ]
