# Generated by Django 5.1.2 on 2025-05-15 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='container_type',
            field=models.CharField(choices=[('BIDONES', 'Bidones (60L)'), ('IBC', 'IBC (1000L)')], default='BIDONES', max_length=10, verbose_name='Tipo de Envase'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='container_type',
            field=models.CharField(choices=[('BIDONES', 'Bidones (60L)'), ('IBC', 'IBC (1000L)')], default='BIDONES', max_length=10, verbose_name='Tipo de Envase'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='liters_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Litros Recolectados'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por Litro'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='liters_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Litros Recolectados'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por Litro'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Precio Total'),
        ),
    ]
