# Generated by Django 5.1.2 on 2025-08-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collection_liters_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
    ]
