# Generated by Django 5.1.2 on 2026-01-26 20:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collection_disabled_historicalcollection_disabled_and_more'),
        ('route', '0007_alter_routedayclient_unique_together_and_more'),
        ('user', '0008_historicalworker_birth_date_worker_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='liters_collected',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='route',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='liters_collected',
        ),
        migrations.RemoveField(
            model_name='historicalcollection',
            name='route',
        ),
        migrations.AddField(
            model_name='collection',
            name='deduction_liters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Litros descontados'),
        ),
        migrations.AddField(
            model_name='collection',
            name='deduction_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas descuento'),
        ),
        migrations.AddField(
            model_name='collection',
            name='deduction_reason',
            field=models.CharField(choices=[('WATER', 'Agua'), ('RESIDUE', 'Residuos/posos'), ('MIXED', 'Mezcla/impurezas'), ('OTHER', 'Otros')], default='RESIDUE', max_length=20, verbose_name='Motivo descuento'),
        ),
        migrations.AddField(
            model_name='collection',
            name='estimated_liters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Litros estimados'),
        ),
        migrations.AddField(
            model_name='collection',
            name='measured_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Litros medidos (brutos)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='net_liters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Litros netos (facturables)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='route_day_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='route.routedayclient', verbose_name='Parada planificada'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='deduction_liters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Litros descontados'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='deduction_notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas descuento'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='deduction_reason',
            field=models.CharField(choices=[('WATER', 'Agua'), ('RESIDUE', 'Residuos/posos'), ('MIXED', 'Mezcla/impurezas'), ('OTHER', 'Otros')], default='RESIDUE', max_length=20, verbose_name='Motivo descuento'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='estimated_liters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Litros estimados'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='measured_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Litros medidos (brutos)'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='net_liters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Litros netos (facturables)'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='route_day_client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='route.routedayclient', verbose_name='Parada planificada'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='container_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Envases'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio por Litro'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('PENDING_MEASUREMENT', 'Pendiente de medición'), ('CONFIRMED', 'Confirmada'), ('CANCELED', 'Cancelada')], default='PENDING_MEASUREMENT', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='container_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Envases'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio por Litro'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='status',
            field=models.CharField(choices=[('PENDING_MEASUREMENT', 'Pendiente de medición'), ('CONFIRMED', 'Confirmada'), ('CANCELED', 'Cancelada')], default='PENDING_MEASUREMENT', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Precio Total'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('route_day_client__isnull', False), models.Q(('status', 'CANCELED'), _negated=True)), fields=('route_day_client',), name='uniq_active_collection_per_route_day_client'),
        ),
    ]
