# Generated by Django 5.1.2 on 2026-02-07 12:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_remove_collection_liters_collected_and_more'),
        ('route', '0008_routeday_daily_capacity_liters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminación')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ANSWERED', 'Respondida'), ('AUTO_ESTIMATED', 'Autoestimada'), ('MANUAL', 'Manual')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('container_type', models.CharField(choices=[('BIDONES', 'Bidones (60L)'), ('IBC', 'IBC (1000L)')], default='BIDONES', max_length=10, verbose_name='Tipo de envase')),
                ('container_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de envases')),
                ('estimated_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Litros estimados')),
                ('final_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Litros finales')),
                ('final_source', models.CharField(blank=True, choices=[('CLIENT', 'Cliente'), ('AUTO', 'Automático'), ('MANUAL', 'Manual')], max_length=10, null=True, verbose_name='Fuente final')),
                ('route_day_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_request', to='route.routedayclient', verbose_name='Parada planificada')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalCollectionRequest',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('disabled', models.BooleanField(default=False, verbose_name='Deshabilitado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminación')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ANSWERED', 'Respondida'), ('AUTO_ESTIMATED', 'Autoestimada'), ('MANUAL', 'Manual')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('container_type', models.CharField(choices=[('BIDONES', 'Bidones (60L)'), ('IBC', 'IBC (1000L)')], default='BIDONES', max_length=10, verbose_name='Tipo de envase')),
                ('container_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de envases')),
                ('estimated_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Litros estimados')),
                ('final_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Litros finales')),
                ('final_source', models.CharField(blank=True, choices=[('CLIENT', 'Cliente'), ('AUTO', 'Automático'), ('MANUAL', 'Manual')], max_length=10, null=True, verbose_name='Fuente final')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route_day_client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='route.routedayclient', verbose_name='Parada planificada')),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelos Base',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
