# Generated by Django 5.1.2 on 2026-02-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_collectionrequest_historicalcollectionrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionrequest',
            options={'verbose_name': 'Solicitud de Recogida', 'verbose_name_plural': 'Solicitudes de Recogida'},
        ),
        migrations.AlterModelOptions(
            name='historicalcollectionrequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Solicitud de Recogida', 'verbose_name_plural': 'historical Solicitudes de Recogida'},
        ),
    ]
