# Generated by Django 5.1.2 on 2026-02-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0008_alter_collectionrequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionrequest",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Respondida en"),
        ),
        migrations.AddField(
            model_name="collectionrequest",
            name="auto_estimate_scheduled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Autoestimacion programada en"),
        ),
        migrations.AddField(
            model_name="collectionrequest",
            name="auto_estimate_task_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID de tarea de autoestimacion"),
        ),
        migrations.AddField(
            model_name="collectionrequest",
            name="manual_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Actualizada manualmente en"),
        ),
        migrations.AddField(
            model_name="collectionrequest",
            name="answered_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="answered_collection_requests", to=settings.AUTH_USER_MODEL, verbose_name="Respondida por"),
        ),
        migrations.AddField(
            model_name="collectionrequest",
            name="manual_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manual_collection_requests", to=settings.AUTH_USER_MODEL, verbose_name="Actualizada manualmente por"),
        ),
        migrations.AddField(
            model_name="historicalcollectionrequest",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Respondida en"),
        ),
        migrations.AddField(
            model_name="historicalcollectionrequest",
            name="auto_estimate_scheduled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Autoestimacion programada en"),
        ),
        migrations.AddField(
            model_name="historicalcollectionrequest",
            name="auto_estimate_task_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID de tarea de autoestimacion"),
        ),
        migrations.AddField(
            model_name="historicalcollectionrequest",
            name="manual_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Actualizada manualmente en"),
        ),
        migrations.AddField(
            model_name="historicalcollectionrequest",
            name="answered_by",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Respondida por"),
        ),
        migrations.AddField(
            model_name="historicalcollectionrequest",
            name="manual_by",
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Actualizada manualmente por"),
        ),
    ]
