# Generated by Django 5.1.2 on 2026-03-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_collectionrequest_traceability_and_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='billable',
            field=models.BooleanField(default=True, verbose_name='Facturable'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='billable',
            field=models.BooleanField(default=True, verbose_name='Facturable'),
        ),
    ]
