# Generated by Django 5.1.2 on 2026-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_collection_billable_historicalcollection_billable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalcollection',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
        migrations.AlterField(
            model_name='historicalcollectionrequest',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='historicalcollectionrequest',
            name='deleted_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AlterField(
            model_name='historicalcollectionrequest',
            name='modified_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de Modificacion'),
        ),
    ]
